set(_CATKIN_CURRENT_PACKAGE "assignment4_trackingandfollowing")
set(assignment4_trackingandfollowing_VERSION "0.0.0")
set(assignment4_trackingandfollowing_MAINTAINER "siqi <siqi@todo.todo>")
set(assignment4_trackingandfollowing_PACKAGE_FORMAT "2")
set(assignment4_trackingandfollowing_BUILD_DEPENDS "cv_bridge" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(assignment4_trackingandfollowing_BUILD_EXPORT_DEPENDS "cv_bridge" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(assignment4_trackingandfollowing_BUILDTOOL_DEPENDS "catkin")
set(assignment4_trackingandfollowing_BUILDTOOL_EXPORT_DEPENDS )
set(assignment4_trackingandfollowing_EXEC_DEPENDS "cv_bridge" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(assignment4_trackingandfollowing_RUN_DEPENDS "cv_bridge" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(assignment4_trackingandfollowing_TEST_DEPENDS )
set(assignment4_trackingandfollowing_DOC_DEPENDS )
set(assignment4_trackingandfollowing_URL_WEBSITE "")
set(assignment4_trackingandfollowing_URL_BUGTRACKER "")
set(assignment4_trackingandfollowing_URL_REPOSITORY "")
set(assignment4_trackingandfollowing_DEPRECATED "")