set(_CATKIN_CURRENT_PACKAGE "assignment3a_team4")
set(assignment3a_team4_VERSION "0.0.0")
set(assignment3a_team4_MAINTAINER "siqi <siqi@todo.todo>")
set(assignment3a_team4_PACKAGE_FORMAT "2")
set(assignment3a_team4_BUILD_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(assignment3a_team4_BUILD_EXPORT_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(assignment3a_team4_BUILDTOOL_DEPENDS "catkin")
set(assignment3a_team4_BUILDTOOL_EXPORT_DEPENDS )
set(assignment3a_team4_EXEC_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(assignment3a_team4_RUN_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(assignment3a_team4_TEST_DEPENDS )
set(assignment3a_team4_DOC_DEPENDS )
set(assignment3a_team4_URL_WEBSITE "")
set(assignment3a_team4_URL_BUGTRACKER "")
set(assignment3a_team4_URL_REPOSITORY "")
set(assignment3a_team4_DEPRECATED "")