set(_CATKIN_CURRENT_PACKAGE "assignment1b")
set(assignment1b_VERSION "0.0.0")
set(assignment1b_MAINTAINER "siqi <siqi@todo.todo>")
set(assignment1b_PACKAGE_FORMAT "2")
set(assignment1b_BUILD_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(assignment1b_BUILD_EXPORT_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(assignment1b_BUILDTOOL_DEPENDS "catkin")
set(assignment1b_BUILDTOOL_EXPORT_DEPENDS )
set(assignment1b_EXEC_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(assignment1b_RUN_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(assignment1b_TEST_DEPENDS )
set(assignment1b_DOC_DEPENDS )
set(assignment1b_URL_WEBSITE "")
set(assignment1b_URL_BUGTRACKER "")
set(assignment1b_URL_REPOSITORY "")
set(assignment1b_DEPRECATED "")