set(turtlebot3_autorace_msgs_MESSAGE_FILES "/home/siqi/Spring_2023/AuE8230Spring23_SiqiZheng/AuE8230Spring23_SiqiZheng/catkin_ws/src/turtlebot3_autorace_2020/turtlebot3_autorace_msgs/msg/MovingParam.msg")
set(turtlebot3_autorace_msgs_SERVICE_FILES "")
